### PR TITLE
Add support for Django 2.0

### PR DESCRIPTION
**Pull request by sjamaan**
The only thing blocking this is the super() call in PartialIndex,
because Index has been changed to allow calling it only with keyword
args, not positional args.

Tweak Travis config to build only Django 2.0 for Python3 versions.

### CODE REVIEW

**Comment by sjamaan** [comment]
ok, never mind. This was a bit premature; the sql creation has been refactored, so this won't work (it only seemed to work for my application)

**Comment by mattiaslinnap** [comment]
Hi @sjamaan 

It was a bit trickier due to that refactoring inside Django, but there is now a pre-relase version for Django 2.0: https://github.com/mattiaslinnap/django-partial-index/pull/7

Does that look like it would work for you?

**Comment by sjamaan** [comment]
Looks good, thanks for the update!

**Comment by mattiaslinnap** [comment]
Version 0.4.0 with Django2 support is now available on PyPI, and as a release on github.

**Pull request closed without merging**
