### PR TITLE
Add "PartialUniqueValidations" mixin for validating partial indexes

### PR DESCRIPTION
**Pull request by sjamaan**
First off, many thanks for creating this project! First-class partial index support really was exactly what I needed for my project after introducing soft deletes (aaaargh!), which made the regular `unique_together` constraints useless. I tried to do it manually with raw SQL in migrations and custom `clean()` methods, but that's not very maintainable in the long run.

But, after moving to this package noticed ticket #4 (I had already seen this issue after removing my `clean()` methods). So, I decided to fix it. This introduces a mixin that the user must include to get proper validation like `unique_together` offers. The mixin adds a custom `validate_unique` method to the model which validates all the `PartialIndex`es which have `unique=True`. I don't really like requiring a mixin, as it's yet another thing for the user to remember, but the alternative would probably be to automatically monkey-patch the user's model class, which is (IMHO) a lot worse.

The reason I had to include a mixin is that Django doesn't really make uniqueness checks pluggable. A better solution (but perhaps more controversial) would be to have `unique_together` be a list of tuples or objects, much like `indexes`. Then if it's an object, its class could determine how to check its constraint and we wouldn't need a mixin. As you can see there's quite a bit of code I had to copy/paste from Django's internal implementation of `validate_unique`; this would also become unnecessary when `unique_together` accepted objects.

Some things this PR does not address:
- Testing of model inheritance. There is quite a bit of machinery in the Django internals I copied which deal with a hierarchy of model classes, but I believe this is hard to support with the current design of the `WHERE` clause as raw SQL string. Might be worthwhile to investigate if `Q` expressions can be used to express the partial index condition? This could then be compiled to a WHERE clause via the regular Django query building mechanism, and might even reduce the need to have different clauses for SQLite and Postgres. I don't know if that's achievable at all.  Backwards compatibility could be kept by checking whether the object is a string or a Q expression.
- Tests could be expanded to explicitly test for skipping validations on missing/invalid fields. Right now I just copied the code to deal with that from Django so it _should_ just work, but it might be worthwhile to nail this down.
- Tests should probably include a test that the original `validate_unique` is still called so that any standard `unique_together` field tuples are still honored.
- As explained above, there's a lot of stuff that's copied from the Django internals. If the implementation details of Django's models change (it's not a public well-defined API) that might mean this code needs to be changed too, as it's relatively tightly coupled to the internals. For example, it uses `_state.adding` to detect when we're saving a new object and `_get_pk_val()` to get the PK. It also uses `model_class._default_manager.db` to fetch this model's database connection (so it should fully support multi-db connections! Except, that's untested too).

### CODE REVIEW

**Comment by sjamaan** [comment]
> The reason I had to include a mixin is that Django doesn't really make uniqueness checks pluggable. A better solution (but perhaps more controversial) would be to have unique_together be a list of tuples or objects, much like indexes.

Alternatively, simply supporting a `unique=True` option in standard indexes with some code to delegate the validations to those `Index` objects should suffice. The `unique_together` would then be redundant, strictly speaking, so could eventually be dropped (I prefer the `unique_together` syntax to the vebosity of `indexes`, but Django deprecated `index_together`, too).

**Comment by mattiaslinnap** [comment]
I've written something similar for my own projects, but I haven't released it yet as I did not yet get to a good solution (maybe still should?).

The main complexity comes from the fact that the partial "where conditions" may contain fields which are not listed in the Index's `fields` parameter. For example, consider the `Job` model's unique index on `group where is_complete = false`: https://github.com/mattiaslinnap/django-partial-index/blob/master/tests/testapp/models.py#L28

Following Django's form validation for standard full unique constraints, it would check if another row with the same `group` exists in the database, and raise error if yes. For the partial unique constraint validation, we have to raise the error *only if also `is_complete = 0` on the new* object. Because you can insert a duplicate group if the *new* object doesn't match the where condition, even if some existing ones do. But parsing the referenced fields from the text-based where conditions is tricky. 

The best solution I found so far is to actually run the `object.save()` during validation in a temporary transaction, turn any IntegrityError into ValidationError, and rollback on success. But this is not acceptable if models override `.save()` to modify fields before save, have pre_save/post_save signals, or similar.

I think a good solution would need replacing the "where conditions" with Django Q-expressions, or alternatively a "where referenced fields" parameter for the PartialIndex?
In essence, we need a way to determine "will this new object match the partial index condition" before actually saving it to the DB.

**Comment by sjamaan** [comment]
> Following Django's form validation for standard full unique constraints, it would check if another row with the same group exists in the database, and raise error if yes.
> For the partial unique constraint validation, we have to raise the error only if also is_complete = 0 on the new object. Because you can insert a duplicate group if the new object doesn't match the where condition, even if some existing ones do.
> But parsing the referenced fields from the text-based where conditions is tricky.

Yeah, actually attempting to parse the text would definitely be the wrong approach. I was thinking more along the lines of using a `Q` object to set the constraint. This should be compilable to a SQL expression, both as part of the constraint or when performing the check. For complex situations, one might still drop down to using a `RawSQL` object instead of a `Q`.

**Comment by mattiaslinnap** [comment]
Refactoring `where_posgresql` and `where_sqlite` to take Q objects instead is definitely the next step in improving this package! It will get rid of the silly syntax differences between PostgreSQL and SQLite, and make it harder to create invalid indexes.

For simple (that's 99% of practical use cases) Q objects, it should be possible to also parse the condition, and use it in the validation mixin.

However, it is not a 100% solution. Q objects can be complex expressions with many fields, functions, etc, and generate the valid SQL expression for that. There is however no good method that I know of of testing a Q object against a Django model instance before it is present in the database. So if someone has a silly partial unique constraint ("no duplicate room bookings on weekdays, allowed on weekends"), they may have to write the validation by hand. But I've never actually seen a partial unique constraint like that used in practice.

**Comment by sjamaan** [comment]
> There is however no good method that I know of of testing a Q object against a Django model instance before it is present in the database. 

As far as I know that's not required. At least, my current mixin simply builds a query that filters objects with the same tuple of unique fields as the in-memory object, and then dumps the `WHERE` condition into the query. If a record exists (with a different PK than the in-memory object, if it has one), it's not unique. I don't see how `Q` objects should make that any more difficult.

**Comment by mattiaslinnap** [comment]
The situation where I can see this approach failing is:

* Model like the Job in https://github.com/mattiaslinnap/django-partial-index/blob/master/tests/testapp/models.py#L28 , with index `PartialIndex(fields=['group'], unique=True, where=Q(is_complete=False))
* There are two existing rows in the DB: `group=A, is_complete=False` and `group=A, is_complete=True`. These can coexist because the partial index only covers is_complete=False.
* Now attempting to add one more row with `group=A, is_complete=True`.

The query that is constructed to find conflicts would look similar to `EXISTS(SELECT 1 FROM job WHERE group='A' AND is_complete=False)`. The `group='A'` comes from the indexed fields and values from the new object, and `is_complete=False` comes from the index where-condition.

This row exists already in the DB, and the validation would raise a duplicate error. But in reality the insert is acceptable, *because the new object being inserted is not covered by the index where-condition*, and no duplicate checking should be done at all.

Now thinking about this, maybe it can be fixed by the following more complex validation query:
1. Filter by fields in the index with values from the new object (like full unique indexes),
2. Exclude by primary key if it exists (to allow updates),
3. Filter by the where-condition on the index,
4. *Filter by all fields referenced in the where-condition, with values from the new object.*

Steps up to 3 are in this PR, but it seems to me that they can incorrectly report a duplicate for the case I described above. I haven't thought this through in detail yet, but at first it seems to me that steps 3+4 together would construct a query that always evaluates to false if the new object does not match the where-condition?

**Comment by sjamaan** [comment]
D'oh! I obviously didn't think it through enough. I had started to type a response here before I thought "but hey, my patch already handles this". I definitely need more coffee :)

In any case, I think a 100% solution would be to compile a query on validation, which unions the data from the table with the record in memory like this:

```sql
WITH existing_records AS (
    SELECT "group"
    FROM job
    WHERE is_complete = False 
    -- AND pk != <saved_object_pk>

    UNION ALL

    SELECT "group"
    FROM (
        SELECT <saved_object_pk> AS id, 'A' AS "group", True AS "is_complete"
    ) AS record_to_save
    WHERE is_complete = False
)
SELECT COUNT(*) AS count
FROM existing_records
```

Then check in Python whether `count <= 1`. This allows us to just dump the `WHERE` from the partial index into both parts of the query. The hard part is generating the UNION and the in-memory subselect that is generated with the values of the current object. I don't know enough black magic to make the Django ORM do my bidding, yet...

**Pull request closed without merging**
